name: Build Pre-Release
on: 
  push:
    tags:
      - '**'
  workflow_dispatch:
  # pull_request:

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linux32_build:
    name: Linux x86 Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: docker run --rm -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:x86-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' }}
      run: tar czf subconverter_linux32.tar.gz subconverter
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: subconverter_linux32
        path: subconverter_linux32.tar.gz

  linux64_build:
    name: Linux x86_64 Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: docker run --rm -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' }}
      run: tar czf subconverter_linux64.tar.gz subconverter
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: subconverter_linux64
        path: subconverter_linux64.tar.gz

  armv7_build:
    name: Linux armv7 Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1-'"$SHA"'/' src/version.h
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build
      run: docker run --rm -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:armv7-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' }}
      run: tar czf subconverter_armv7.tar.gz subconverter
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: subconverter_armv7
        path: subconverter_armv7.tar.gz

  aarch64_build:
    name: Linux aarch64 Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1-'"$SHA"'/' src/version.h
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Build
      run: docker run --rm -v $GITHUB_WORKSPACE:/root/workdir multiarch/alpine:aarch64-latest-stable /bin/sh -c "apk add bash git nodejs npm && cd /root/workdir && chmod +x scripts/build.alpine.release.sh && bash scripts/build.alpine.release.sh"
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' }}
      run: tar czf subconverter_aarch64.tar.gz subconverter
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: subconverter_aarch64
        path: subconverter_aarch64.tar.gz

  macos_build:
    name: macOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i -e 's/\(v[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: bash scripts/build.macos.release.sh
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' }}
      run: tar czf subconverter_darwin64.tar.gz subconverter
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: subconverter_darwin64
        path: subconverter_darwin64.tar.gz

  windows64_build:
    name: Windows x86_64 Build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel git mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-pcre2 patch
        msystem: MINGW64
        path-type: inherit
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: bash scripts/build.windows.release.sh
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' }}
      run: 7z a subconverter_win64.7z subconverter/
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: subconverter_win64
        path: subconverter_win64.7z

  windows32_build:
    name: Windows x86 Build
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel git mingw-w64-i686-gcc mingw-w64-i686-cmake mingw-w64-i686-pcre2 patch
        msystem: MINGW32
        path-type: inherit
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\+\.[0-9]\+\.[0-9]\+\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: bash scripts/build.windows.release.sh
    - name: Package Release
      if: ${{ github.event_name != 'pull_request' }}
      run: 7z a subconverter_win32.7z subconverter/
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: subconverter_win32
        path: subconverter_win32.7z

  Upload-Prerelease:
    name: Upload-Prerelease
    needs: [linux32_build, linux64_build, armv7_build, aarch64_build, windows64_build, macos_build, windows32_build]
    runs-on: ubuntu-latest
    steps:
    - name: Download
      uses: actions/download-artifact@v3
    - name: Display structure of downloaded files
      run: ls -R
    - name: Delete old Pre-release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: Pre-release
        github_token: ${{ secrets.GITHUB_TOKEN }}
        delete_release: true

    - name: Tag Repo
      uses: richardsimko/update-tag@v1
      with:
        tag_name: Pre-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Pre-release
      uses: softprops/action-gh-release@v1
      if: ${{  success() }}
      with:
        tag_name: Pre-release
        files: |
          ./subconverter_linux32/*
          ./subconverter_linux64/*
          ./subconverter_armv7/*
          ./subconverter_aarch64/*
          ./subconverter_darwin64/*
          ./subconverter_win64/*
          ./subconverter_win32/*
        prerelease: true
        generate_release_notes: true

    - name: Release Changelog Builder
      uses: mikepenz/release-changelog-builder-action@v4.1.1
